### ISSUE TITLE
Not working on 1.18.2

### ISSUE THREAD

**Issue by joex92** [sachingorkar102/Tweakin#39]
```yaml
[05:58:02 INFO]: [Tweakin] Enabling Tweakin v3.8.5
[05:58:02 INFO]: [Tweakin] Running papermc..
[05:58:02 INFO]: [Tweakin] Running v1_18_R2 ...
[05:58:02 WARN]: java.lang.ClassNotFoundException: com.github.sachin.tweakin.nms.v1_18_R2.NMSHandler
[05:58:02 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153)
[05:58:02 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105)
[05:58:02 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[05:58:02 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[05:58:02 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[05:58:02 WARN]:        at Tweakin-3.8.5.jar//com.github.sachin.tweakin.nbtapi.NBTAPI.loadVersions(NBTAPI.java:22)
[05:58:02 WARN]:        at Tweakin-3.8.5.jar//com.github.sachin.tweakin.Tweakin.onEnable(Tweakin.java:74)
[05:58:02 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[05:58:02 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[05:58:02 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[05:58:02 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[05:58:02 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[05:58:02 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669)
[05:58:02 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436)
[05:58:02 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:352)
[05:58:02 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1179)
[05:58:02 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
[05:58:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[05:58:02 WARN]: [Tweakin] Running incompataible version, stopping tweakin
[05:58:02 INFO]: [Tweakin] Disabling Tweakin v3.8.5
```

**Comment by RemyyB** [comment]
Hey there! I built it from source to support 1.18.2, take a look at the Discord > #general-support :)

**Comment by joex92** [comment]
@RemyyB can you give me the discord inv? and the message link? 😅

**Comment by RemyyB** [comment]
@joex92 sure! Discord invite is: https://discord.gg/AQpgKXwUdN
Message link: https://discord.com/channels/838260272347086868/912527364884422686/968802176354902026

**Comment by sachingorkar102** [comment]
added
