### ISSUE TITLE
Tweakin 4.0.0 Not Working on 1.18.2

### ISSUE THREAD

**Issue by moderator10000078** [sachingorkar102/Tweakin#40]
[18:25:34 WARN]: java.lang.ClassNotFoundException: com.github.sachin.tweakin.nms.v1_18_R2.NMSHandler
[18:25:34 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153)
[18:25:34 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105)
[18:25:34 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[18:25:34 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[18:25:34 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[18:25:34 WARN]:        at Tweakin-4.0.0.jar//com.github.sachin.tweakin.nbtapi.NBTAPI.loadVersions(NBTAPI.java:22)
[18:25:34 WARN]:        at Tweakin-4.0.0.jar//com.github.sachin.tweakin.Tweakin.onEnable(Tweakin.java:74)
[18:25:34 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:25:34 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:25:34 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[18:25:34 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[18:25:34 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[18:25:34 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669)
[18:25:34 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436)
[18:25:34 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:352)
[18:25:34 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1179)
[18:25:34 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
[18:25:34 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[18:25:34 WARN]: [Tweakin] Running incompataible version, stopping tweakin

**Comment by sachingorkar102** [comment]
1.18.2 will be supported soon

**Comment by sachingorkar102** [comment]
added
