### ISSUE TITLE
Compatibility with Teak's Tweaks broken

### ISSUE THREAD

**Issue by kayaven** [sachingorkar102/Tweakin#71]
## Server info:
```
[19:34:27 INFO]: [bootstrap] Running Java 21 (OpenJDK 64-Bit Server VM 21.0.4+7-LTS; Azul Systems, Inc. Zulu21.36+17-CA) on Windows 10 10.0 (amd64)
[19:34:27 INFO]: [bootstrap] Loading Paper 1.21-102-master@aa3b356 (2024-07-20T17:42:49Z) for Minecraft 1.21
```

## Relevant server logs:
```
[19:34:37 INFO]: [Tweakin] Enabling Tweakin v8.0.0
[19:34:37 INFO]: [Tweakin] Running papermc..
[19:34:37 INFO]: [Tweakin] [PriLib] Running 1.21 minecraft version
[19:34:37 INFO]: [Tweakin] [ACF] Enabled Asynchronous Tab Completion Support!
[19:34:37 INFO]: [Tweakin] Loading tweakin...
[19:34:37 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[19:34:37 INFO]: [Tweakin] Generating Head Map, this might take a while...
[19:34:37 INFO]: [Tweakin] Generated 198 mob heads..
[19:34:37 ERROR]: Error occurred while enabling Tweakin v8.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: me/teakivy/teakstweaks/Main
        at Tweakin-8.1.0.jar/com.github.sachin.tweakin.compat.TeaksTweaksCompat.isPackEnabled(TeaksTweaksCompat.java:15) ~[Tweakin-8.1.0.jar:?]
        at Tweakin-8.1.0.jar/com.github.sachin.tweakin.BaseTweak.reload(BaseTweak.java:76) ~[Tweakin-8.1.0.jar:?]
        at Tweakin-8.1.0.jar/com.github.sachin.tweakin.TweakItem.reload(TweakItem.java:38) ~[Tweakin-8.1.0.jar:?]
        at Tweakin-8.1.0.jar/com.github.sachin.tweakin.manager.TweakManager.reload(TweakManager.java:157) ~[Tweakin-8.1.0.jar:?]
        at Tweakin-8.1.0.jar/com.github.sachin.tweakin.manager.TweakManager.load(TweakManager.java:96) ~[Tweakin-8.1.0.jar:?]
        at Tweakin-8.1.0.jar/com.github.sachin.tweakin.Tweakin.onEnable(Tweakin.java:134) ~[Tweakin-8.1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-102-aa3b356]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-102-aa3b356]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-102-aa3b356]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-102-aa3b356]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.jar:1.21-102-aa3b356]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.jar:1.21-102-aa3b356]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-102-aa3b356]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.jar:1.21-102-aa3b356]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-102-aa3b356]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.teakivy.teakstweaks.Main
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 18 more
[19:34:37 INFO]: [Tweakin] Disabling Tweakin v8.0.0
[19:34:37 ERROR]: Error occurred while disabling Tweakin v8.0.0
java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "this.permissions" is null
        at Tweakin-8.1.0.jar/com.github.sachin.tweakin.Tweakin.onDisable(Tweakin.java:189) ~[Tweakin-8.1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.jar:1.21-102-aa3b356]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.jar:1.21-102-aa3b356]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.jar:1.21-102-aa3b356]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-102-aa3b356]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-102-aa3b356]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-102-aa3b356]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.jar:1.21-102-aa3b356]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.jar:1.21-102-aa3b356]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-102-aa3b356]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.jar:1.21-102-aa3b356]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-102-aa3b356]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```
Note: I am running `Tweakin-8-1.0.jar`, even though the logs say `Enabling Tweakin v8.0.0`.

From what I could tell from the source code of this repo, you check in `src/main/java/com/github/sachin/tweakin/compat/TeaksTweaksCompat.java` for class `me.teakivy.teakstweaks.Main.class`. This class no longer exists when I inspect the latest version of the .jar file of Teak's Tweaks. Seems that it has been renamed to `TeaksTweaks.class`.

Not sure if any other incompatibilities exist by now other than this change.

Thanks in advance!

**Comment by sachingorkar102** [comment]
pretty bold of him to change the main class file now, lol
i will look into it
